import {ACTIONS,CLASSES,FOES,progression,depthFromY,attackBonus,defenceStats,playerAttackRating,playerDefenceRating,weightedPick,rngInt,clamp,xpToNext,maxHp} from './core.js';
import {generateEquipmentDrop,equipmentAffixTotalsFor,formatGold} from './equipment.js';

const STRIKE_MULT=[1,1.6,2.6];
const INTENT_LABEL={quick:'Quick Attack',heavy:'Heavy Attack',dodge:'Dodge',guard:'Guard',recover:'Recover',steady:'Steady'};
const INTENT_TELL={quick:'testing the opening at once',heavy:'drawing back for a committed blow',dodge:'shifting its weight to evade',guard:'setting itself behind its guard',recover:'giving ground to recover',steady:'trying to regain its balance'};

export class Combat{
  constructor({game,world,ui,onEnd,onDeath,onSave}){this.game=game;this.world=world;this.ui=ui;this.onEnd=onEnd;this.onDeath=onDeath;this.onSave=onSave;this.active=false;this.armed=null;this.entity=null;this.foe=null;this.playerSprite=world.player;this.foeSprite={x:0,y:0,renderOffsetX:0,renderOffsetY:0};this.locked=false;}
  start(entity){
    if(this.active)return;this.active=true;this.entity=entity;const depth=depthFromY(entity.y),base=entity.foe||FOES[0],prog=progression(depth);const scaleHp=prog.primary/13,scaleAtk=prog.enemyHit/8;
    const maxHp=Math.max(8,Math.round(base.hp*scaleHp*(.94+Math.random()*.12)));this.foe={base,name:base.name,maxHp,hp:maxHp,atk:Math.max(1,Math.round(base.atk*scaleAtk)),xp:Math.max(base.xp,Math.round(base.xp*scaleHp)),stamina:0,intent:null,heavyStage:0,guard:false,dodge:false,blind:false,offBalance:false,read:false};
    this.foeSprite.x=entity.x;this.foeSprite.y=entity.y;this.foeSprite.foe=base;this.world.combatFoe=this.foeSprite;this.world.combatEntityId=entity.id;this.positionCombatants();this.game.player.stamina=3;this.game.player.strikeChain=0;this.game.player.prepared=null;this.armed=null;this.rollIntent();this.ui.showCombat(true);this.ui.combatMessage(`<b>${this.foe.name}</b> closes the distance.`);this.render();this.onSave?.();
  }
  positionCombatants(){const dx=this.entity.x-this.playerSprite.x,dy=this.entity.y-this.playerSprite.y,len=Math.hypot(dx,dy)||1;const ux=dx/len,uy=dy/len;this.foeSprite.x=this.playerSprite.x+ux*52;this.foeSprite.y=this.playerSprite.y+uy*52;this.entity.x=this.foeSprite.x;this.entity.y=this.foeSprite.y;}
  actions(){const cls=CLASSES[this.game.player.className]||CLASSES.Votary;const heavyName=this.game.player.className==='Rogue'?'Backstab':this.game.player.className==='Wizard'?'Arcane Bolt':'Heavy';return Object.entries(ACTIONS).map(([id,a])=>({id,...a,name:id==='defend'?cls.defend:id==='heavy'?heavyName:a.name}));}
  render(){if(!this.active)return;this.ui.renderCombat(this,this.actions());}
  preview(id){if(this.locked||!this.active)return;const a=ACTIONS[id];if(!a)return;if(id!=='end'&&id!=='run'&&a.cost>this.game.player.stamina)return;this.armed=this.armed===id?null:id;if(this.armed===id)this.ui.combatMessage(this.previewText(id));else this.ui.combatMessage('Choose an action. Tap once to preview, again to commit.');this.render();}
  async choose(id){if(this.locked||!this.active)return;const a=ACTIONS[id];if(!a)return;if(id!=='end'&&id!=='run'&&a.cost>this.game.player.stamina)return;if(this.armed!==id){this.preview(id);return;}this.armed=null;this.locked=true;try{await this.resolvePlayer(id);}finally{this.locked=false;if(this.active)this.render();}}
  previewText(id){const p=this.game.player,ab=attackBonus(playerAttackRating(p)),fds=defenceStats(this.enemyDefenceRating());const need=clamp(fds.ac-ab,2,20);const labels={strike:`Strike · ${ACTIONS.strike.cost} Stamina · d20 +${ab} vs AC ${fds.ac} · needs ${need}+`,heavy:`Heavy · full turn · 3.2× damage · normal accuracy`,defend:`${CLASSES[p.className].defend} · reduce the next incoming hit by ${Math.round(CLASSES[p.className].defendReduction*100)}%`,counter:`Counter · +4 AC against the next attack; retaliate if it misses`,sand:`Sand · 60% Blind; a blinded foe's next attack misses`,read:`Read · learn ${this.foe.name}'s weakness for this run`,end:`End Turn · give the foe its turn`,run:`Run · escape but lose ${Math.max(1,Math.round(p.hpMax*.1))} HP`};return labels[id]||'';}
  enemyAttackRating(){const depth=depthFromY(this.entity.y);return progression(depth).primary;}
  enemyDefenceRating(){const depth=depthFromY(this.entity.y);return progression(depth).defence;}
  rollD20(){return rngInt(1,20);}
  hitRoll(attBonus,targetAc){const d=this.rollD20();return{d,total:d+attBonus,hit:d===20||(d!==1&&d+attBonus>=targetAc),crit:d===20};}
  weaponBase(){return playerAttackRating(this.game.player);}
  async resolvePlayer(id){const p=this.game.player;if(id==='end'){p.stamina=0;this.ui.combatMessage('You yield the rest of the turn.');await this.enemyTurn();return;}if(id==='run'){const cost=Math.max(1,Math.round(p.hpMax*.1));p.hp=Math.max(1,p.hp-cost);this.ui.combatMessage(`<span class="bad">You break away, losing ${cost} HP.</span>`);await this.wait(220);this.end(false,'run');return;}const cost=ACTIONS[id].cost;p.stamina=Math.max(0,p.stamina-cost);
    if(id==='strike'||id==='heavy')await this.playerAttack(id);else if(id==='defend'){p.prepared={type:'defend'};this.ui.combatMessage(`You set ${CLASSES[p.className].defend.toLowerCase()} for the next attack.`);}else if(id==='counter'){p.prepared={type:'counter'};this.ui.combatMessage('You leave a narrow opening and prepare the counter.');}else if(id==='sand'){if(Math.random()<.6){this.foe.blind=true;this.ui.combatMessage('<span class="good">The sand catches its eyes. Blinded.</span>');}else this.ui.combatMessage('The sand scatters wide.');}else if(id==='read'){this.foe.read=true;p.knowledge[this.foe.base.id]=(p.knowledge[this.foe.base.id]||0)+1;this.ui.combatMessage(`<span class="good">Known weakness:</span> ${this.foe.base.weakness}`);}
    if(!this.active)return;if(p.stamina<=0)await this.enemyTurn();else this.render();this.onSave?.();
  }
  async playerAttack(kind){const p=this.game.player,ab=attackBonus(playerAttackRating(p)),eds=defenceStats(this.enemyDefenceRating());let ac=eds.ac+(this.foe.dodge?4:0);const roll=this.hitRoll(ab,ac);const mult=kind==='heavy'?3.2:STRIKE_MULT[p.strikeChain||0];await this.bump(this.playerSprite,this.foeSprite,14);
    if(!roll.hit){p.strikeChain=0;this.ui.combatMessage(`<span class="bad">d20 ${roll.d} + ${ab} = ${roll.total} vs AC ${ac}. Miss.</span>`);this.foe.dodge=false;return;}
    let dmg=Math.max(1,Math.round(this.weaponBase()*mult+rngInt(0,kind==='heavy'?6:4)));if(this.foe.guard)dmg=Math.max(1,Math.round(dmg*(kind==='heavy'?.85:.50)));if(this.foe.offBalance)dmg=Math.round(dmg*(this.foe.base.id==='mauler'?1.5:1.25));if(roll.crit)dmg*=2;
    this.foe.hp=Math.max(0,this.foe.hp-dmg);this.world.spawnText(this.foeSprite.x,this.foeSprite.y,roll.crit?`CRIT ${dmg}`:`-${dmg}`);this.ui.combatMessage(`${roll.crit?'<span class="crit">Natural 20 · CRITICAL.</span> ':''}<b>${dmg}</b> damage.`);this.foe.guard=false;this.foe.dodge=false;this.foe.offBalance=false;if(kind==='strike')p.strikeChain=((p.strikeChain||0)+1)%3;else p.strikeChain=0;if(this.foe.hp<=0){await this.wait(260);this.victory();}}
  rollIntent(){if(!this.active)return;if(this.foe.heavyStage===1){this.foe.intent='heavy';this.foe.heavyStage=2;return;}const weights={...this.foe.base.intents};if(this.foe.hp/this.foe.maxHp<(this.foe.base.recoverAt||.3))weights.recover=(weights.recover||0)+20;this.foe.intent=weightedPick(weights);if(this.foe.intent==='heavy')this.foe.heavyStage=1;}
  async enemyTurn(){if(!this.active)return;const p=this.game.player;await this.wait(260);const intent=this.foe.intent;
    if(intent==='heavy'&&this.foe.heavyStage===1){this.foe.heavyStage=2;this.foe.intent='heavy';this.ui.combatMessage(`<span class="bad">${this.foe.name} winds up a Heavy Attack.</span>`);this.newPlayerTurn();return;}
    if(intent==='guard'){this.foe.guard=true;this.ui.combatMessage(`${this.foe.name} settles behind its guard.`);this.rollIntent();this.newPlayerTurn();return;}
    if(intent==='dodge'){this.foe.dodge=true;this.ui.combatMessage(`${this.foe.name} shifts into a dodge.`);this.rollIntent();this.newPlayerTurn();return;}
    if(intent==='recover'){const heal=Math.max(1,Math.round(this.foe.maxHp*.14));this.foe.hp=Math.min(this.foe.maxHp,this.foe.hp+heal);this.ui.combatMessage(`${this.foe.name} recovers <span class="good">${heal} HP</span>.`);this.rollIntent();this.newPlayerTurn();return;}
    await this.enemyAttack(intent);if(!this.active)return;if(intent==='heavy')this.foe.heavyStage=0;this.rollIntent();this.newPlayerTurn();
  }
  async enemyAttack(intent){const p=this.game.player,ab=attackBonus(this.enemyAttackRating()),baseDef=defenceStats(playerDefenceRating(p)),counter=p.prepared?.type==='counter',ac=baseDef.ac+(counter?4:0);let roll=this.hitRoll(ab,ac);if(this.foe.blind){roll.hit=false;this.foe.blind=false;}await this.bump(this.foeSprite,this.playerSprite,14);
    if(!roll.hit){this.ui.combatMessage(`<span class="good">${this.foe.name} misses.</span> d20 ${roll.d} + ${ab} vs AC ${ac}.`);if(counter){p.prepared=null;await this.wait(120);await this.counterRetaliation();}else p.prepared=null;return;}
    const mult=intent==='quick'?.6:intent==='heavy'?2:1;let dmg=Math.max(1,Math.round(this.foe.atk*mult*(.92+Math.random()*.16)*(1-baseDef.deflection)));if(roll.crit)dmg*=2;if(p.prepared?.type==='defend')dmg=Math.max(1,Math.round(dmg*(1-CLASSES[p.className].defendReduction)));p.prepared=null;p.hp=Math.max(0,p.hp-dmg);this.world.spawnText(this.playerSprite.x,this.playerSprite.y,roll.crit?`CRIT ${dmg}`:`-${dmg}`);let extra='';const reflect=equipmentAffixTotalsFor(p).reflect;if(reflect.pct>0){const returned=Math.min(reflect.damageCap,Math.max(0,Math.round(dmg*reflect.pct/100)));if(returned>0){this.foe.hp=Math.max(0,this.foe.hp-returned);this.world.spawnText(this.foeSprite.x,this.foeSprite.y,`-${returned}`);extra=` <span class="good">Reflect returns ${returned}.</span>`;}}this.ui.combatMessage(`${roll.crit?'<span class="crit">Natural 20 · CRITICAL.</span> ':''}<span class="bad">${this.foe.name} hits for <b>${dmg}</b>.</span>${extra}`);if(this.foe.hp<=0){await this.wait(200);this.victory();return;}if(intent==='heavy')this.foe.offBalance=true;if(p.hp<=0){await this.wait(250);this.death();}}
  async counterRetaliation(){if(!this.active)return;const p=this.game.player;await this.bump(this.playerSprite,this.foeSprite,15);let dmg=Math.max(1,Math.round(this.weaponBase()*2+rngInt(0,4)));if(p.knowledge[this.foe.base.id])dmg=Math.round(dmg*1.5);this.foe.hp=Math.max(0,this.foe.hp-dmg);this.world.spawnText(this.foeSprite.x,this.foeSprite.y,`-${dmg}`);this.ui.combatMessage(`<span class="good">Counter retaliation auto-hits for <b>${dmg}</b>.</span>`);if(this.foe.hp<=0){await this.wait(220);this.victory();}}
  newPlayerTurn(){if(!this.active)return;this.game.player.stamina=3;this.armed=null;this.render();}
  victory(){if(!this.active)return;const p=this.game.player,depth=this.game.currentDepth,key=this.foe.base.id;p.kills++;p.xp+=this.foe.xp;let coin=0;if(Math.random()<.58)coin=rngInt(1,5)+Math.floor(progression(depth).g/18);p.gold+=coin;const drops=[];if(key==='scrounger'&&(p.inventory.rogueTools||0)<=0&&Math.random()<.12){p.inventory.rogueTools=1;drops.push('Rogue Tools');}if(Math.random()<.34){const r=Math.random();if(r<.38){p.inventory.meat++;drops.push('Meat');}else if(r<.67){p.inventory.bandages++;drops.push('Bandage');}else if(r<.78){p.inventory.water++;drops.push('Water');}else if(r<.88){p.inventory.rope++;drops.push('Rope');}else if(r<.96){p.inventory.campSupplies++;drops.push('Camp Supply');}else{p.inventory.misc=p.inventory.misc||{};p.inventory.misc['Scroll Dust']=(p.inventory.misc['Scroll Dust']||0)+1;drops.push('Scroll Dust');}}while(p.xp>=xpToNext(p.level)){p.xp-=xpToNext(p.level);p.level++;p.statPoints++;p.hpMax=maxHp(p);}let gear=null;const chance=key==='oldhand'?.36:(key==='shieldback'||key==='mauler')?.30:.24;if(Math.random()<chance)gear=generateEquipmentDrop(p,depth,key);this.world.markFoeDefeated(this.entity);this.world.spawnText(this.foeSprite.x,this.foeSprite.y,'DEFEATED');const loot=[coin?formatGold(coin):'',...drops,gear?.name||''].filter(Boolean).join(' · ');this.ui.combatMessage(`<span class="good">Defeated.</span> +${this.foe.xp} XP${loot?` · ${loot}`:''}.`);this.end(true,'victory');}
  death(){const p=this.game.player;p.dead=true;this.active=false;this.world.setCombat(false);this.ui.showCombat(false);this.onDeath?.(this.foe.name);this.onSave?.();}
  end(won,reason){if(!this.active&&reason!=='victory')return;this.active=false;this.world.setCombat(false);this.ui.showCombat(false);this.armed=null;this.onEnd?.({won,reason,entity:this.entity,foe:this.foe});this.onSave?.();}
  bump(a,b,amount){return new Promise(resolve=>{this.world.bump(a,b,amount,.22,()=>{setTimeout(resolve,70)});setTimeout(resolve,260);});}
  wait(ms){return new Promise(r=>setTimeout(r,ms));}
  intentLabel(){return INTENT_LABEL[this.foe?.intent]||'Unknown';}
  intentTell(){if(this.foe?.intent==='heavy'&&this.foe.heavyStage===2)return 'the committed blow is ready to release';return INTENT_TELL[this.foe?.intent]||'';}
}
